### PR TITLE
Default iterations per namespace for cni heavy

### PR DESCRIPTION
**Pull request by afcollins**
### Fixes ...

... failures running node-density-heavy and node-density-cni @245ppn on clusters with more than 24 worker nodes.

### CODE REVIEW

**Comment by jtaleric** [comment]
Thoughts on renaming the workload to `cni-heavy-v2`? I fear people might just compare the results when they shouldn't really be compared...

**Comment by afcollins** [comment]
My thoughts on that are: this is intended to be a replacement. I don't think the current configuration (245ppn in 1 namespace) should be run at all going forward.

Maybe we have a cutover period in the next readouts that run old & new config, but honestly the current config doesn't provide meaningful results, hence trying to erase it.

**Comment by jtaleric** [comment]
> My thoughts on that are: this is intended to be a replacement. I don't think the current configuration (245ppn in 1 namespace) should be run at all going forward.

ack. ➕  My concern is people (not in our team) taking this new test and comparing it to prior runs. 

> 
> Maybe we have a cutover period in the next readouts that run old & new config, but honestly the current config doesn't provide meaningful results, hence trying to erase it.

**Comment by afcollins** [comment]
I consulted the two known consumers (QE and ACS), and neither are using ocp wrapper to run cni and heavy that they would be affected by this change.

The e2e-benchmarking parameters from kube-burner-ocp-wrapper use the defaults defined in the wrapper. I learned from Paige they have not migrated the jobs with cni or heavy to the e2e ocp-wrapper, so I proposed  to wait until these changes are merged and can work at that time to (hopefully) get more meaningful results out of the test.

I added missing documentation for the config variable, and a note to clarify the behavior.

If we want to add some note to the next release notes or something to call it out, I am happy to do that.

**Comment by afcollins** [comment]
Looks like a flake to me. I can't find a re-run option anywhere.

**Review by rsevilla87 — APPROVED** [review]
lgtm!

**Pull request merged**
