### PR TITLE
New web-burner ocp wrapper

### PR DESCRIPTION
**Pull request by josecastillolema**
## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [x] Documentation Update

## Description

New OCP wrapper for the [web-burner workload](https://github.com/redhat-performance/web-burner). The idea is to migrate the workload into the repo and decomission the old repository.

CI related tests to this specific workload will be handled in a separate PR.

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests
   - It is not a core feature, and CI related tests to this specific workload will be handled in a separate CR

## Local testing

Thanks to https://github.com/cloud-bulldozer/kube-burner/pull/523 it is possible to test this workload locally:
```
$ ./kind.sh --install-cni-plugins --disable-snat-multiple-gws --multi-network-enable
$ kubectl label node ovn-worker node-role.kubernetes.io/worker-spk="" --overwrite=true
$ ./kube-burner ocp web-burner-init --gc=false --sriov=false --bridge=breth0 --alerting=false --local-indexing=false
$ ./kube-burner ocp web-burner-node-density --gc=false --sriov=false --bridge=breth0 --alerting=false --local-indexing=false --probe=true
$ kubectl get po -A | grep serving | grep Running | wc -l
4
$ kubectl get po -A | grep served | grep Running | wc -l
61
```

### CODE REVIEW

**Comment by rsevilla87** [comment]
Needs a small rebase

**Comment by vishnuchalla** [comment]
Code changes look good to me. 
@rsevilla87 I think we should slowly start thinking for options to host our canned workload YAML configuration files somewhere remote. I mean to only have GO code in kube-burner (i.e dirver/execution logic) and fetch configurations from remote URLs. As we can see lot many configuration files are being added with our new incoming workloads.

**Comment by vishnuchalla** [comment]
@josecastillolema can you rebase and update the PR, please?

**Comment by josecastillolema** [comment]
Done @vishnuchalla

**Comment by josecastillolema** [comment]
Hi!
The TSCs changes (wb#78) have not yet been merged to main, there were some changes requested and the corresponding documentation is missing.
This PR is synced with web-burner main as of today (04/12), I suggest we merge this if/when the reviewers think is ready, then immediately mark as unmaintained web-burner and migrate that PR (wb#78) and every other web-burner related PR to this repository to avoid maintaining drift from both sides.

**Review by rsevilla87 — APPROVED** [review]
lgtm

**Pull request merged**
