### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by smalleni**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [X] Documentation Update

Add a code of conduct from a GitHub provided template. Please make any suggestions for improvement.

### CODE REVIEW

**Review by jtaleric — CHANGES_REQUESTED** [review]
https://github.com/cloud-bulldozer/.github 

This is actually inherited already.. 
image

**Comment by smalleni** [comment]
> https://github.com/cloud-bulldozer/.github
> 
> This is actually inherited already.. image

Perhaps, but I am trying to satisfy a list of requirements to get CNCF sandbox status, and we need a code of conduct within the repo.

**Comment by jtaleric** [comment]
Maybe consider using :  https://github.com/cncf/foundation/blob/main/code-of-conduct.md If this is specific to the CNCF.

**Comment by smalleni** [comment]
> Maybe consider using : https://github.com/cncf/foundation/blob/main/code-of-conduct.md If this is specific to the CNCF.

Yeh I considered using that. However reading the text of it, it doesn't seem like it is something that could be referenced by a non CNCF project. I can see a scenario where once we are accepted, we move over and just point to the CNCF guide.

**Comment by jtaleric** [comment]
> > Maybe consider using : https://github.com/cncf/foundation/blob/main/code-of-conduct.md If this is specific to the CNCF.
> 
> Yeh I considered using that. However reading the text of it, it doesn't seem like it is something that could be referenced by a non CNCF project. I can see a scenario where once we are accepted, we move over and just point to the CNCF guide.

ack - 

No issues here... Thanks for the additional context.

**Review by vishnuchalla — APPROVED** [review]

**Comment by vishnuchalla** [comment]
@rook is this good to go?

**Review by jtaleric — APPROVED** [review]

**Pull request merged**
